<?php

namespace AppBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {

        $qb = $this->createQueryBuilder('m');
        $qb->select('count(m)');

        return $count = $qb->getQuery()->getSingleScalarResult();

    }
}
